@hostJob = http://192.168.3.16:7000
@hostHome = http://192.168.1.14:7000

@host = {{hostJob}}

@email = "admin@admin.ru"
@password = "admin"
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLnJ1IiwiaWQiOjEsInJvbGVzIjpbeyJpZCI6MSwibmFtZSI6ImFkbWluIiwiZGVzY3JpcHRpb24iOiLQkNC00LzQuNC90LjRgdGC0YDQsNGC0L7RgCIsImRlbGV0ZWRBdCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyMy0xMC0wNlQxMzoxMDoxMi4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMy0xMC0wNlQxMzoxMDoxMi4wMDBaIn1dLCJiYW5uZWQiOmZhbHNlLCJpYXQiOjE2OTgzODYwODMsImV4cCI6MTY5ODQyMjA4M30.EqlmDFSNtAGNsu1KpP7lSGWkSIbG1rbY2aMUDFcfqaI

### ------ Объекты ---------------------------------------------------------
### Получение объектов
GET {{host}}/objects HTTP/1.1
Authorization: Bearer {{token}}


### Создание объекта
POST {{host}}/objects HTTP/1.1
Authorization: Bearer {{token}}
Content-type: application/json; charset=utf-8

{
    "name": "Зеландия",
    "address": "г. Пенза"
}

###

POST {{host}}/objects HTTP/1.1
Authorization: Bearer {{token}}
Content-type: application/json; charset=utf-8

{
    "name": "Континент",
    "address": "г. Пенза"
}

###
POST {{host}}/objects HTTP/1.1
Authorization: Bearer {{token}}
Content-type: application/json; charset=utf-8

{
    "name": "Лугометрия",
    "address": "г. Пенза"
}

### Получение информации по одному объекту
GET {{host}}/objects/getData/2 HTTP/1.1
Authorization: Bearer {{token}}

###

### Получение списка с информацией по одному объекту
GET {{host}}/objects/shortData/ HTTP/1.1
Authorization: Bearer {{token}}

###