export { authApi } from "./auth";
export { listNameWorkApi } from "./listNameWork";
export { mainApi, mainManagerApi, objectMainApi } from "./main";
export { nameWorkApi } from "./nameWork";
export { objectsApi } from "./objects";
export { orderReceiptApi } from "./orderReceipt";
export { providerApi } from "./provider";
export { roleApi } from "./roles";
export { scopeWorkApi } from "./scopeWork";
export { storageApi } from "./storage";
export { tableAddingDataApi } from "./tableAddingData";
export { transportCompanyApi } from "./transportCompany";
export { typeWorkApi } from "./typeWork";
export { unitsApi } from "./units";
export { userDescriptionApi } from "./userDescription";
export { userApi } from "./users";
