version: "3.1"
services:
    redis_main:
        image: redis
        container_name: redis_main
        restart: always
        ports:
            - 16379:6379
        volumes:
            - redis_data:/data
volumes:
    redis_data:
