@hostJob = http://192.168.3.16:7000
@hostHome = http://192.168.1.14:7000

@host = {{hostJob}}

@email = "admin@admin.ru"
@password = "admin"
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLnJ1IiwiaWQiOjEsInJvbGVzIjpbeyJpZCI6MSwibmFtZSI6ImFkbWluIiwiZGVzY3JpcHRpb24iOiLQkNC00LzQuNC90LjRgdGC0YDQsNGC0L7RgCIsImRlbGV0ZWRBdCI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyMy0xMC0wNlQxMzoxMDoxMi4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMy0xMC0wNlQxMzoxMDoxMi4wMDBaIn1dLCJiYW5uZWQiOmZhbHNlLCJpYXQiOjE2OTY4Mjg1NzIsImV4cCI6MTY5Njg2NDU3Mn0.sS-OW9LeDCOqKO1V4MU6HbEytoz1qjRQrOTQKdYbTLk





### ------ User ---------------------------------------------------------------

### Получение объектов
GET {{host}}/user/withData HTTP/1.1


### Получение объектов
GET {{host}}/user HTTP/1.1
//Authorization: Bearer {{token}}


### Получение одного
GET {{host}}/user/2 HTTP/1.1
//Authorization: Bearer {{token}}

### Получение объектов
GET {{host}}/user/objectsUser/2 HTTP/1.1
//Authorization: Bearer {{token}}


### Получение статистики
GET {{host}}/user/getStatistics/2 HTTP/1.1


### Получение объёмов
GET {{host}}/user/scopeWorkUser/2 HTTP/1.1

###  Получим все листы для одного пользователя
GET {{host}}/user/allListUser/1 HTTP/1.1


### Редактирование пользователя
GET {{host}}/user/edit/1 HTTP/1.1

### Изменяем роли
POST {{host}}/user/updateRoles/1 HTTP/1.1
Content-type: application/json; charset=utf-8

### []
### ["admin","user"]
### ["admin"]
### ["user"]
