import {
    IDataError,
    IObjectCreateAttr,
    IObjectCreateResponse,
    IUserLogin,
    IUserRegister,
    IUserResponseToken,
} from "./api";
import {
    IAuthSlice,
    ICreateNameWorkAttr,
    INameWorkAndUnit,
    INameWorkCreateResponse,
    IRole,
    ITypeWork,
    IUnit,
    IUnitsCreateAttr,
    IUser,
    IUserDescription,
    IUserToken,
    IUsersSlice,
} from "./models";
import { IInputFormItemProps, IInputPasswordFormItemProps } from "./ui";

export type {
    IAuthSlice,
    ICreateNameWorkAttr,
    IDataError,
    IInputFormItemProps,
    IInputPasswordFormItemProps,
    INameWorkAndUnit,
    INameWorkCreateResponse,
    IObjectCreateAttr,
    IObjectCreateResponse,
    IRole,
    ITypeWork,
    IUnit,
    IUnitsCreateAttr,
    IUser,
    IUserDescription,
    IUserLogin,
    IUserRegister,
    IUserResponseToken,
    IUserToken,
    IUsersSlice,
};
